name: nb_utils
description: This package helps you daily usable function with ease. Just add nb_utils with its latest version and that's it you are ready to use.
version: 4.3.0+2
homepage: https://bhoominn.github.io
repository: https://github.com/bhoominn/nb_utils
issue_tracker: https://github.com/bhoominn/nb_utils/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  shared_preferences: ^2.0.6
  fluttertoast: ^8.0.7
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.nb.nb_utils
        pluginClass: NbUtilsPlugin
      ios:
        pluginClass: NbUtilsPlugin
      linux:
        pluginClass: nb_utils_plugin
      macos:
        pluginClass: NbUtilsPlugin
      windows:
        pluginClass: nb_utils_plugin
      web:
        pluginClass: NbUtilsWeb